version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
            - "3000:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "../laravel-shared-multitenancy:/var/www/html"
        depends_on:
            - php
            - mysqldb
    php:
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../laravel-shared-multitenancy:/var/www/html"
    composer:
        image: "composer"
        volumes:
            - "../laravel-shared-multitenancy:/app"
        command: install
    mysqldb:
        image: mysql
        container_name: ${DB_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_USER=${DB_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
